image: orai/cosmwasm-gitpod:0.11.7
workspaceLocation: '${GITPOD_REPO_ROOT}'

tasks:
  - name: init-cargo-file
    init: touch Cargo.toml && echo ${GITPOD_REPO_ROOT}

vscode:
  extensions:
    - matklad.rust-analyzer
    - oraichain.cosmwasm-ide
