image: orai/cosmwasm-gitpod:0.11.7
workspaceLocation: GITPOD_REPO_ROOT

tasks:
  - name: init-cargo-file
    init: cd ${GITPOD_REPO_ROOT} && touch Cargo.toml

vscode:
  extensions:
    - matklad.rust-analyzer
    - oraichain.cosmwasm-ide
